import { Module } from '@nestjs/common';
import { GraphQLModule } from "@nestjs/graphql";
import { MercuriusDriver, MercuriusDriverConfig } from "@nestjs/mercurius";
import * as path from "path";
import { UserModule } from "@okkino/feature-user";

@Module({
  imports: [
    GraphQLModule.forRoot<MercuriusDriverConfig>({
      graphiql: true,
      driver: MercuriusDriver,
      autoSchemaFile: path.join(__dirname, './autogenerated-schema.gql')
    }),
    UserModule
  ],
  providers: [],
})
export class AppModule {}
